### ISSUE TITLE
Rename Uploaded Files

### ISSUE THREAD

**Issue by JordanNash** [agentile/S3-Media-Storage#10]
Thanks for this awesome plugin!

When I set up the Cloudfront domain name setting, I used the internal name (_.cloudfront.net/_) instead of cdn.example.com/*. I uploaded the first batch of files before I realized my mistake. Now, a bunch of files have the internet URL path instead of the nicer URL. 

Could you add a rewrite feature to fix the names of previously uploaded files when the Cloudfront setting changes?

Thanks!

**Comment by JordanNash** [comment]
I fixed the entries directly in MySQL. For those interested, here's the procedure:

Log into your server using SSH.
mysql -u [dbusername] -p
USE [wordpress-db];
UPDATE wp_postmeta SET meta_value='cdn.example.com' WHERE meta_value LIKE '%cloudfront.net';

**Comment by agentile** [comment]
Thanks!
