### ISSUE TITLE
Add some filters/hooks in your plugin

### ISSUE THREAD

**Issue by talha-asad** [agentile/S3-Media-Storage#3]
Hi,

Great plugin, however i have to add in filters and hooks myself. Was thinking that maybe we can decide on some basic filters and hooks for this plugin so its easy for people to further enhance on this plugin's capabilities. In my case i need to know when a file is uploaded to media library / S3.

Let me know what you think, i can submit a PR, once we decide on what hooks should be appropriate. 

Thanks.

**Comment by agentile** [comment]
Yeah, I always welcome pull requests, I just switched the plugin to be more OOP style, so hopefully that will make things easier to do so. Cheers!
