### ISSUE TITLE
Warning in debug mode

### ISSUE THREAD

**Issue by rogerlos** [agentile/S3-Media-Storage#4]
In admin.php on line 6:

`add_options_page('S3 Media Storage', 'S3 Media Storage', '4', 'S3MSAdminMenu', 'S3MSAdminContent');`

The "4" is causing WP to throw a deprecated warning. You should change this to a capability, I changed it to 'edit_files' as that's an admin/superadmin level, but it can be anything that seems right.

`add_options_page('S3 Media Storage', 'S3 Media Storage', 'edit_files', 'S3MSAdminMenu', 'S3MSAdminContent');`

**Comment by agentile** [comment]
Fixed this
