### ISSUE TITLE
If no value is entered for bucket path, adds it to URL anyway

### ISSUE THREAD

**Issue by rogerlos** [agentile/S3-Media-Storage#5]
I believe this is because line 58 of s3-media-storage is:

``` php
$bucket_path = isset($custom_fields['S3MS_bucket_path']) ? 
$custom_fields['S3MS_bucket_path'][0] : null;
```

This will always return true, I believe, because you are creating the meta field regardless of it having a value on line 230 of s3-media-storage.php:

``` php
update_post_meta($attachment_id, "S3MS_bucket_path", $settings['s3_bucket_path']);
```

The `get_post_custom` key 'S3MS_bucket_path' referenced by the first block will contain an empty array, and will therefore evaluate to true. Which means that lines 93 and 99 will always be used to build the path:

``` html
http://my.bucket.s3.amazonaws.com//dork.jpg
```

Amazon, in this case, adds a directory with no name to your bucket, and, indeed, you can call the images from there if you paste that URL into your browser bar, but it seemingly breaks the media library as that set of double-slashes is ignored by the browser, php or wordpress, or some combination thereof, and

``` html
http://my.bucket.s3.amazonaws.com/dork.jpg
```

does not exist. That's what I'm guessing is happening, anyway.

Thanks for the work on this plugin!

**Comment by rogerlos** [comment]
I was totally wrong, of course--still needs fixing, but it's not caused by the above. This is an Windows server artifact, at least on my server. In s3-media-storage.php, this:

``` php
$file = str_replace($upload_dir['baseurl'], '', $url);
if (substr($file, 0, 1) == DIRECTORY_SEPARATOR) {
    $file = substr($file, 1);
}
```

Will never fire the "if" clause, since WP always saves the string with a forward slash, and on IIS DIRECTORY_SEPARATOR will be the silly backslash. Changing DIRECTORY_SEPARATOR to "/" fixed this issue.

**Comment by agentile** [comment]
Fixed this, thanks!
