### ISSUE TITLE
Random results

### ISSUE THREAD

**Issue by TraciBunkers** [agentile/S3-Media-Storage#6]
I'm getting very random results uploading media--sometimes it uploads, transfers to S3 bucket & changes the URL to my couldfrount domain and sometimes it doesn't. Sometimes I get an http error when I upload. Even with the http error, sometimes it still uploads the photo, transfers it to S3 & changes the URL, sometimes it doesn't. I haven't figured out any pattern to it. I have turned off all plugins and used a default theme, and have the same results. If I turn off the plugin, I don't get the http error uploading media.

At first I thought I always had to tell the plugin to manually transfer the images until I asked on your blog and you said it should do it automatically. When I do manually tell the plugin to transfer them, it doesn't change the URL in the post (maybe it's not supposed to). And if I use something like Velvet Blues Update URLs to change the URLs in the posts, it shows part of the URL duplicated in the S3 media page settings. But if I look through the database, the URLs aren't duplicated like that.

For example, after I change the URLs with the Velvet Blues Update URL plugin, on the S3 Media settings page, it'll show the S3 file as https://d2k2naxhvn4zw5.cloudfront.net/blog/wp-content/uploads/http://d2k2naxhvn4zw5.cloudfront.net/blog/wp-content/uploads/2014/03/TraciBunkers.com-031214-journalpage.jpg

If I turn off the plugin, then none of the thumbnails show for the images that I uploaded or transferred using the plugin unless I turn on W3 total cache. But even with W3 TC on, the thumbnails in the media library still don't show in the admin unless I turn the plugin back on. I've been doing all these tests without W3 TC on, but noticed it helped with the thumbnail issue if I turned it on.

So, as you can see, I'm having issues.

I'm using WP 3.8.1 and my site is hosted on a server that uses CloudLinux (in case that makes a difference).

**Comment by agentile** [comment]
Traci,

```
Yeah, the plugin doesn't go back and modify posts in any way, It deals strictly with the media in the library, so if you upload a new file or replace one with a newer version, then the updates should happen correspondingly for that media. If you are using another plugin to do URL changing, I really can't guarantee consistency with my S3 urls that I am building.
```

I've just updated the plugin to fix some other issues, let me know if it helps your http errors. Thanks
