### ISSUE TITLE
Menu won't show up in Settings

### ISSUE THREAD

**Issue by gabrielpopa** [agentile/S3-Media-Storage#7]
I changed add_options_page in admin.php to:

add_options_page('S3 Media Storage', 'S3 Media Storage', 'manage_options', 'S3MSAdminMenu', 'S3MSAdminContent');

That way I was able to view the Option in Settings. (wordpress 3.8.1)

**Comment by TraciBunkers** [comment]
Thank you! I couldn't find the settings, and never would have figured this out myself.

**Comment by agentile** [comment]
Fixed in master.

**Comment by agentile** [comment]
Thank you
